### ISSUE TITLE
how to identify number of active subscribers by subscription in AppSync

### ISSUE THREAD

**Issue by kushptlapigarage** [aws-samples/aws-appsync-visualization-with-athena-app#2]
Need to keep count of how many subscribers are connected with each subscription.

For UserA, UserB are connected with SubscriptionA : then 2 is the total subscribers
For UserA are connected with SubscriptionB : then 1 is the total subscribers

Can i know when UserA unsubscribes , subscribes, disconnects, reconnects from AppSync ?

**Comment by onlybakam** [comment]
Please take a look a tthis blog: https://aws.amazon.com/blogs/mobile/appsync-realtime/

specifically highlighted:

> Furthermore with the new protocol support we’re also increasing visibility on WebSockets connections and GraphQL subscriptions activity with CloudWatch metrics on active connections and subscriptions, status, errors, message size and more.

and https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html#cw-metrics
