### ISSUE TITLE
errorType: "MappingTemplate"

### ISSUE THREAD

**Issue by cnbrkkaya** [aws-samples/aws-appsync-visualization-with-athena-app#9]
Hi,
I tried to deploy the application via amplify console, i set the athena correctly. I tried the execute sql command via athena console it works but when i tried to use the application from the front-end i select the country code and click query button but i get these error in the console and i cannot get the data from appsync.

querry failed -> 
errorType: "MappingTemplate"
message: "Unable to convert     $utils.appendError($ctx.result.body.Message, $ctx.result.statusCode)↵ to class java.lang.Object."

I didnt change the request and response mapping templates and i cant figure out what is wrong.
Thanks for your help.

**Comment by vmakarevich** [comment]
DId you find a solution???

**Comment by cnbrkkaya** [comment]
No i am not able to find a solution.

**Comment by onlybakam** [comment]
i wasnt able to reproduce. but can you try this again with the udpated codebase

**Comment by onlybakam** [comment]
lack of response. closing the issue.
